steps:
  # Run tests
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        python -m pytest tests/ --cov=./ --cov-report=xml
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  # Security scanning
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud components install local-extract
        gcloud beta code vulnerability-test ./

  # Build container
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/iot-monitoring-api:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/iot-monitoring-api:latest',
      '.'
    ]

  # Push to registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/iot-monitoring-api']

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=k8s/
    - --image=gcr.io/$PROJECT_ID/iot-monitoring-api:$COMMIT_SHA
    - --cluster=iot-monitoring-cluster
    - --location=us-central1
    - --namespace=default

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'